# Generated by Django 3.2.4 on 2021-06-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0010_auto_20210623_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='ciudad',
            field=models.TextField(default=''),
        ),
    ]
