# Generated by Django 3.2.4 on 2021-06-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0011_alter_vuelo_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedaje',
            name='ciudad',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='ciudad',
            field=models.TextField(default=''),
        ),
    ]
