# Generated by Django 3.2.4 on 2021-06-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0012_auto_20210623_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospedaje',
            old_name='presio',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='presio',
            new_name='preCio',
        ),
        migrations.RenameField(
            model_name='vuelo',
            old_name='presio',
            new_name='precio',
        ),
    ]
