# Generated by Django 3.2.4 on 2021-06-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0013_auto_20210624_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='preCio',
            new_name='precio',
        ),
    ]
