# Generated by Django 3.2.4 on 2021-06-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0014_rename_precio_viaje_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='descrpicion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='vuelo',
            old_name='descrpicion',
            new_name='descripcion',
        ),
    ]
